// --- IMPORT CONFIG ---
// DO NOT EDIT THIS BLOCK - IT IS GENERATED BY THE ADMIN PANEL
// ✅ FIXED: Removed unsafe eval() method
const supabaseUrl = typeof SHADOW_AI_CONFIG !== 'undefined' ? SHADOW_AI_CONFIG.supabaseUrl : "";
const supabaseKey = typeof SHADOW_AI_CONFIG !== 'undefined' ? SHADOW_AI_CONFIG.supabaseKey : "";

// ✅ UNIVERSAL: Works on Chrome, Edge, Brave & All Browsers
let COMPANY_ID = "";
async function loadIdFromStorage() {
    try {
        // Check which API is available (Chrome or Standard)
        let storage = chrome || browser;
        
        const data = await storage.storage.local.get(['shadow_company_id']);
        if (data.shadow_company_id) {
            COMPANY_ID = data.shadow_company_id;
            console.log("✅ ID Loaded from Login:", COMPANY_ID);
        } else {
            // Fallback to config file if storage is empty
            COMPANY_ID = typeof SHADOW_AI_CONFIG !== 'undefined' ? SHADOW_AI_CONFIG.companyId : "";
        }
    } catch (e) {
        console.log("Falling back to config file", e);
        COMPANY_ID = typeof SHADOW_AI_CONFIG !== 'undefined' ? SHADOW_AI_CONFIG.companyId : "";
    }
}

let customSecrets = [];
const deviceFingerprint = `${navigator.platform} | ${navigator.userAgent.substring(0, 100)}`;

// ==========================================
// ✅ THE ULTIMATE BLACKLIST DATABASE
// ==========================================
const securityPatterns = [
    // IDENTITY & CONTACT
    { name: "EMAIL_ADDRESS", regex: /[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}/gi },
    
    // FINANCIAL
    { name: "CREDIT_CARD", regex: /\b\d{4}[- ]?\d{4}[- ]?\d{4}[- ]?\d{4}\b/g },
    { name: "IBAN_CODE", regex: /[A-Z]{2}\d{2}[A-Z0-9]{4,30}/gi },
    
    // TECH & API SECRETS
    { name: "OPENAI_KEY", regex: /sk-[A-Za-z0-9-_]{20,}/gi },
    { name: "AWS_KEY", regex: /AKIA[0-9A-Z]{16}/gi },
    { name: "GENERIC_API_KEY", regex: /(api|key|token|secret|password|bearer|auth)[^\s]{0,10}['"]?[a-zA-Z0-9_\-+/]{20,}['"]?/gi },
    
    // PERSONAL ID
    { name: "SSN", regex: /\b\d{3}[-]?\d{2}[-]?\d{4}\b/g },
    { name: "IP_ADDRESS", regex: /\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b/g }
];

// ==========================================
// 📡 SYNC WITH ADMIN DASHBOARD
// ==========================================
async function fetchCompanySecrets() {
    if (!COMPANY_ID || COMPANY_ID.length < 3) {
        customSecrets = [];
        return;
    }
    try {
        // Updated to use COMPANY_ID instead of USER_ID
        const response = await fetch(`${supabaseUrl}/rest/v1/company_secrets?select=*&company_id=eq.${COMPANY_ID}`, {
            headers: { "apikey": supabaseKey, "Authorization": "Bearer " + supabaseKey }
        });
        const data = await response.json();
        if (Array.isArray(data)) customSecrets = data;
    } catch (err) { 
        // Fail silently - offline mode
    }
}

// ==========================================
// 📊 REPORT TO ADMIN
// ==========================================
async function reportLeak(type, detail, blockedText = "") {
    if (!COMPANY_ID) return;
    try {
        await fetch(`${supabaseUrl}/rest/v1/security_logs`, {
            method: "POST",
            headers: { 
                "apikey": supabaseKey, 
                "Authorization": "Bearer " + supabaseKey, 
                "Content-Type": "application/json" 
            },
            body: JSON.stringify({
                event_type: type,
                user_device: deviceFingerprint,
                violation_type: detail,
                site_url: window.location.hostname,
                blocked_content: blockedText,
                created_at: new Date(),
                company_id: COMPANY_ID // Updated to Company ID
            })
        });
    } catch (error) {
        // Logging failed, but protection still active
    }
}

// ==========================================
// 🛡️ THE SHADOW BADGE (Visual Proof)
// ==========================================
function addBadge() {
    if (document.getElementById('shadow-ai-badge')) return;

    const badge = document.createElement('div');
    badge.id = 'shadow-ai-badge';
    badge.innerHTML = `🛡️ Shadow AI Active`;
    badge.style.cssText = `
        position: fixed;
        top: 15px;
        right: 15px;
        background: linear-gradient(135deg, #1e3a8a 0%, #000000 100%);
        color: #00ffcc;
        padding: 10px 20px;
        border-radius: 30px;
        font-weight: bold;
        font-size: 13px;
        z-index: 9999999;
        box-shadow: 0 0 25px rgba(0, 255, 200, 0.5);
        border: 1px solid #00ffcc;
        font-family: Arial, sans-serif;
        letter-spacing: 1px;
    `;
    document.body.appendChild(badge);
}

// ==========================================
// ⚡ THE PROTECTION ENGINE
// ==========================================
function scanAndBlock() {
    let globalLeakDetected = false;
    let logMessage = "";

    addBadge();

    // --- PART 1: SCAN INPUT BOXES ---
    const inputs = document.querySelectorAll('textarea, [contenteditable="true"], input[type="text"]');
    inputs.forEach(input => {
        let text = input.value || input.innerText || "";
        if (text.length < 3) return;

        let redactedText = text;
        let localLeak = false;

        // A. Check Custom Words
        customSecrets.forEach(secret => {
            try {
                const safeWord = secret.secret_word.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&');
                const regex = new RegExp(safeWord, 'gi');
                if (regex.test(text)) { 
                    redactedText = redactedText.replace(regex, secret.label || "██████████");
                    localLeak = true;
                    globalLeakDetected = true;
                    logMessage = `Secret: ${secret.secret_word}`;
                }
            } catch(e) {}
        });

        // B. Check System Patterns
        if (!localLeak) {
            securityPatterns.forEach(pattern => {
                if (pattern.regex.test(text)) { 
                    redactedText = redactedText.replace(pattern.regex, `[${pattern.name}]`);
                    if (!localLeak) {
                        localLeak = true;
                        globalLeakDetected = true;
                        logMessage = `Pattern: ${pattern.name}`;
                    }
                }
            });
        }

        // Apply Changes
        if (localLeak) {
            if (input.value !== undefined) input.value = redactedText;
            else input.innerText = redactedText;
            reportLeak("PREVENTED", logMessage, text);
        }
    });

    // --- PART 2: SCAN CHAT HISTORY (Redaction) ---
    customSecrets.forEach(secret => {
        try {
            const regex = new RegExp(secret.secret_word.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&'), 'gi');
            document.querySelectorAll('*').forEach(el => {
                if (el.children.length === 0 && el.innerText && regex.test(el.innerText)) { 
                     if (!el.closest('#shadow-ai-badge')) {
                        el.innerHTML = el.innerHTML.replace(regex, `<span style="background:#000; color:#000; padding:2px 5px; border-radius:4px; font-weight:bold;">${secret.label || 'REDACTED'}</span>`);
                     }
                }
            });
        } catch(e) {}
    });

    // --- PART 3: LOCK SEND BUTTON ---
    const sendButton = document.querySelector('[data-testid="send-button"], button[type="submit"], .send-button');
    if (sendButton) {
        sendButton.disabled = globalLeakDetected;
        sendButton.style.opacity = globalLeakDetected ? "0.3" : "1";
        sendButton.style.cursor = globalLeakDetected ? "not-allowed" : "pointer";
        sendButton.style.transform = globalLeakDetected ? "scale(0.98)" : "scale(1)";
    }
}

// ==========================================
// 🚀 STARTUP SEQUENCE
// ==========================================
loadIdFromStorage().then(() => {
    fetchCompanySecrets();
    setInterval(scanAndBlock, 150); // Ultra Fast Scan
    setInterval(fetchCompanySecrets, 30000); // Sync every 30s
});

// Observer for dynamic content
const observer = new MutationObserver((mutations) => {
    scanAndBlock();
});
observer.observe(document.body, { childList: true, subtree: true, attributes: true });

console.log("%c 🛡️ SHADOW AI GUARD ACTIVE ", "background: black; color: #00ffcc; font-size: 16px");